title: "RPblog"
author: "RP"
description: "RPblog: Just a spot for few blog posts..."

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "rpysny@gmail.com"
#github_username: "githubuser"
#linkedin_username: "linkedinuser"

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_navbar: true # show horizontal navbar
  show_blog: true # show blog posts added in _posts
  show_tags: true # show tags in a blog posts
  back_home_text: "home..."

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
